### ISSUE TITLE
Exceptions in repeated test method are silently swallowed

### ISSUE THREAD

**Issue by sithmein** [cbismuth/junit-repeat-rule#11]
If a test method is annotated with @Repeat any exceptions that are thrown by the method are silently ignored and the test succeeds. Just try the following:

```
@Test
@Repeat(times = 10)
public void test() {
    throw new RuntimeException("Forced exception");
}
```

Obviously this is a complete show-stopper for an otherwise very nice feature.

**Comment by ocafebabe** [comment]
Same problem here! This makes this nice extension pretty much useless!

**Comment by cbismuth** [comment]
@sithmein @ocafebabe sorry I didn't see the GitHub notification ... I'll have a look at it quickly.

**Comment by cbismuth** [comment]
Fix ready, to be polished tomorrow, stay tuned ...

**Comment by cbismuth** [comment]
I propagate the first exception raised (i.e. from the first repetition only). Is it good for you?

**Comment by cbismuth** [comment]
Release created, it will be available in Maven Central soon.
